version: '3'
services:
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      TZ: Asia/Seoul

volumes:
  mysqldata:
    driver: local